### ISSUE TITLE
Application fails to start when the appender is not able to communicate with gray log instance

### ISSUE THREAD

**Issue by PedroHReis22** [pukkaone/logback-gelf#19]
When I try to execute my application using a wrong hostname in the graylog configuration, I got an exception:

```
15:34:26,847 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:34:26,847 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:34:26,847 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:{...}/logback.xml]
15:34:27,009 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:34:27,032 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:{...}/logback.xml]
15:34:27,032 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
15:34:27,035 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:34:27,048 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:34:27,060 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:34:27,180 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:34:27,186 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
15:34:27,208 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@66233253 - No compression will be used
15:34:27,211 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@66233253 - Will use the pattern /var/log/myapplication.%d{yyyy-MM-dd}.log for the active file
15:34:27,217 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/myapplication.%d{yyyy-MM-dd}.log'.
15:34:27,217 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
15:34:27,221 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Oct 16 15:31:51 BRST 2017
15:34:27,223 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:34:27,226 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /var/log/myapplication.log
15:34:27,226 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/var/log/myapplication.log]
15:34:27,228 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:34:27,228 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE_DEBUG]
15:34:27,230 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1286783232 - No compression will be used
15:34:27,230 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1286783232 - Will use the pattern /var/log/myapplication.%d{yyyy-MM-dd}.log for the active file
15:34:27,232 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/myapplication_debug.%d{yyyy-MM-dd}.log'.
15:34:27,232 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
15:34:27,233 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Oct 16 15:32:59 BRST 2017
15:34:27,233 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:34:27,236 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_DEBUG] - Active log file name: /var/log/myapplication_debug.log
15:34:27,236 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE_DEBUG] - File property is set to [/var/log/myapplication_debug.log]
15:34:27,237 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.github.pukkaone.gelf.logback.GelfAppender]
15:34:27,246 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [GRAYLOG]
15:34:35,312 |-ERROR in com.github.pukkaone.gelf.logback.GelfAppender[GRAYLOG] - Unknown Graylog2 hostname [myhost] java.net.UnknownHostException: myhost
	at java.net.UnknownHostException: myhost
	at 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at 	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at 	at com.github.pukkaone.gelf.protocol.GelfUDPSender.<init>(GelfUDPSender.java:37)
	at 	at com.github.pukkaone.gelf.logback.GelfAppender.getGelfUDPSender(GelfAppender.java:214)
	at 	at com.github.pukkaone.gelf.logback.GelfAppender.start(GelfAppender.java:265)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at mypackage.myclass.<clinit>(MyClass.java:14)
	at 	at 
15:34:35,315 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [mylogger] to DEBUG
15:34:35,315 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [...] to false
15:34:35,316 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE_DEBUG] to Logger[...]
15:34:35,317 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:34:35,317 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
15:34:35,317 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:34:35,317 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [GRAYLOG] to Logger[ROOT]
15:34:35,317 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:34:35,320 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@77b52d12 - Registering current configuration as safe fallback point
```

Of course I'm expecting some kind of error once the configuration is wrong, however, the application is not starting when this happens. Is this behavior expected? How can I avoid that?

**Comment by pukkaone** [comment]
Logback by itself will continue if there's something wrong in its configuration. Did you mean your Spring Boot application fails to start? The Spring Boot developers intended for the application to [fail fast by design](https://github.com/spring-projects/spring-boot/issues/3309) when the Logback configuration is incorrect.

**Comment by PedroHReis22** [comment]
@pukkaone, thanks. Is there any feature (from the gelf perspective)  to make an appender optional? I think I can accomplish this using environment variable, but I was looking for something easier.
